version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
  postgres:
    image: "postgres:alpine"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - '5432:5432'